### ISSUE TITLE
Option to auto hold Push To Talk key

### ISSUE THREAD

**Issue by Nothing4You** [Jitnaught/JNSoundboard#1]
Hey there,

EXP Soundboard has a nice feature where you can set a specific key to be pressed while sound is being played, so you don't need to use some push to talk keys manually all the time while playing sounds.

**Comment by Jitnaught** [comment]
I'll look into it. :)

**Comment by Nothing4You** [comment]
Maybe even implement this in a way where there can be a global PTT key or application specific PTT keys in combination with #5

**Comment by Jitnaught** [comment]
Another great idea.
