### ISSUE TITLE
Use WPF instead of Windows Forms

### ISSUE THREAD

**Issue by Nothing4You** [Jitnaught/JNSoundboard#10]
If you don't mind I'd like to change the GUI to WPF soonish.
That'll also make it a lot easier to look at diffs for UI code.

**Comment by Jitnaught** [comment]
If you want to do it go right ahead. I'd probably do it after all the other improvements you suggested are added.

**Comment by Jitnaught** [comment]
I don't think I'll be doing this, as there really won't be any improvement to the program itself. You can still do it if you'd like.
