### ISSUE TITLE
Cant Save Settings

### ISSUE THREAD

**Issue by NYPD** [Jitnaught/JNSoundboard#12]
Hello, I'm afraid I'm unable to save settings for some reason. I only got it to work once, but the rest of the time I get this error:

https://i.imgur.com/pok1YJJ.png

Which is strange because the path is correct:

https://i.imgur.com/jxco5BW.png

And the XML file was populated by the JN Soundboard app:

https://i.imgur.com/iA8QE2L.png

Do you think this might have to do with permissions or the operating system? I am currently using Windows 10 Version 10.0.15063 Build 15063.

**Comment by NYPD** [comment]
Actually, I just looked at the source code (I'm not too proficient with the C family) but in this line of SettingsForm.cs:

```C#
 if (loadXMLFilesList.Count == 0 || loadXMLFilesList.All(x => x.Keys.Length > 0 && !string.IsNullOrWhiteSpace(x.XMLLocation) && File.Exists(x.XMLLocation)))
```

I should be able to save the stop sounds key by itself, but I still get the same error:

https://i.imgur.com/bciWmb2.png

So now I'm thinking maybe it is windows 10 being goofy on the input or something

**Comment by Jitnaught** [comment]
Sorry for the very late reply. Try to see if there is an empty entry in the "Load XML file with keys" list, and deleting it if it's there. I've had the problem before, where there would be an invisible entry there that you don't know about.

**Comment by NYPD** [comment]
No problem, I can't seem to replicate the issue anymore. If it ever comes back up I'll try that solution. 

thanks
