### ISSUE TITLE
Error with adding sound from Text-to-speech

### ISSUE THREAD

**Issue by ykz89** [Jitnaught/JNSoundboard#14]
When adding a sound using the Text-to-speech it adds the 'sound location' as 'window'
![screenshot 2017-06-11 01 52 02](https://user-images.githubusercontent.com/4377149/27007159-91cb2a20-4e49-11e7-92fe-4b68b486d96b.png)

**Comment by Jitnaught** [comment]
Fixed in commit https://github.com/Jitnaught/JNSoundboard/commit/ffab637b1f1971a74c50ee7c11db42370ae7f1f1 :)
