### ISSUE TITLE
Adding a stop all sounds key shows warning

### ISSUE THREAD

**Issue by Siilwyn** [Jitnaught/JNSoundboard#15]
👋 Hi there, I really enjoy using your soundboard but found one issue.

I can't add a stop all sounds shortcut key, after filling it in and pressing okay a dialog opens with "One or more entries either have no keys added, the location is empty, or the file the location points to does not exist". 🤔

**Comment by Jitnaught** [comment]
Fixed in commit https://github.com/Jitnaught/JNSoundboard/commit/7df7fe753d8a8915d5237742aa4f881283a46d35 :)

**Comment by Siilwyn** [comment]
Great, thank you!
