### ISSUE TITLE
Add a play button for playback without hotkey

### ISSUE THREAD

**Issue by Nothing4You** [Jitnaught/JNSoundboard#2]

**Comment by Nothing4You** [comment]
I'll add a PR for this when #8 is merged

**Comment by Jitnaught** [comment]
Not really in my interest, but if you want to work on it, go ahead.

**Comment by Nothing4You** [comment]
Like I said, code is done already, just wanted to get #8 merged first as it is based on that and I want to avoid a merge conflict.
I don't mind doing some of the stuff I added as issues myself.
