### ISSUE TITLE
The actual exe file isn't in the git?...

### ISSUE THREAD

**Issue by nisbahmumtaz** [Jitnaught/JNSoundboard#20]
Hi,

I had to google up JNSoundboard, and download it from a softpedia page.
Granted, I'm kind of a dumbass, so maybe I'm just not accessing the right files to execute it.

Lemme know if my concerns are legit, or just from stupidity. I can take objectivity, it's all good.

**Comment by Jitnaught** [comment]
You can get it from the Releases page: https://github.com/Jitnaught/JNSoundboard/releases

**Comment by nisbahmumtaz** [comment]
Oh, cool.
Maybe a link to that on the front side of the readme with:

You can download new versions from the Releases page: https://github.com/Jitnaught/JNSoundboard/releases

Just for those not used to github? Thanks for the response.

**Comment by Jitnaught** [comment]
Added the link in a435ddb443fce30aee6cb5ace68becddbaf8644f :)
