### ISSUE TITLE
Why limit Push-To-Talk to a specific window?

### ISSUE THREAD

**Issue by t-gebauer** [Jitnaught/JNSoundboard#23]
If you are using Teamspeak with a PTT-hotkey then you probably want to send the key to any window as long as TS is running in the background.

Minor issues:
- Save the PPT-hotkey in the settings?
- Do not change the overall enabled state on changes to the PTT settings?

**Comment by Jitnaught** [comment]
I don't remember exactly why I made it like that. I think it was because (some) games wouldn't detect a virtual key press if it was pressed globally, but it worked when I used the current method. I may look into it.

**Comment by t-gebauer** [comment]
That totally makes sense; especially if the push-to-talk key is only relevant to the one game you are playing. But with an application like Teamspeak, which accepts the key on any foreground application it might come in handy to be able to turn this limit off. Think of games with a separate launcher in a different window; you probably want to speak there too?

**Comment by Jitnaught** [comment]
I'm not sure what you mean by separate launcher?

**Comment by t-gebauer** [comment]
Two windows: a launcher for preparing and matchmaking and a second application; the actual game that only gets opened once a match is found.
The point is, that one might want to use the ptt functionality on different windows.

A simple option to choose whether to limit the ptt key would be a nice feature. (allow empty selection in the list box)

**Comment by Jitnaught** [comment]
Sounds like a good idea, I'll add the functionality today

**Comment by cookieman768** [comment]
Could you potentially compile an updated version? If not, show us how to compile it? I'm very interested in this but I need this update since it's not working in PUBG for some reason.
